version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      CLOUDINARY_NAME: hardart-cz
      CLOUDINARY_KEY: 529325956937259
      CLOUDINARY_SECRET: 8jd-Zp5bvuDvu89uZYHyqr-s2fU
    volumes:
      - ./app:/srv/app
    ports:
      - '1339:1339'
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
